version: '3.7'

services:
  pizza_cassandra_db:
    image: cassandra:4.1.2
    container_name: cassandra_db
    restart: unless-stopped
    ports:
      - "9042:9042"
    networks:
      - cassandra-net

networks:
  cassandra-net:
    driver: bridge