version: '3.7'

services:
  pizza_db:
    image: postgres:12-alpine
    container_name: pizza_db
    ports:
      - "5437:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=pizza_db