spring:
  thymeleaf:
    cache: false
  datasource:
    name: pizzaDb_h2

    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5437}/pizza_service_db
    username: ${POSTGRES_USER:shop_adm}
    password: ${POSTGRES_PASSWORD:root}

pizza:
  orders:
    sizePage: 2
  show:
    page: 0