spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5437}/pizza_service_db
    username: ${POSTGRES_USER:pizza_adm}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true
    open-in-view: false

  profiles:
    active: dev

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jdbc.template.fetch-size: 100

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 213577873753-rkr3kj6od6g8jboibs855tg9ld7m6dhc.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid,email,profile

pizza:
  orders:
    sizePage: 2
  show:
    page: 0

app:
  upload:
    bucket: "/home/naglezh/IdeaProjects/1. myProjects/pizza-service/images"
    buffer-size: 8192