spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: pizzaDb_h2

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pizzaDb_h2
    username: sa
    password:

pizza:
  orders:
    sizePage: 2
  show:
    page: 0

logging:
  level:
    root: info
  file:
    name: pizza-service.log
    path: /