spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5437}/pizza_service_db
    username: ${POSTGRES_USER:pizza_adm}
    password: ${POSTGRES_PASSWORD:root}
  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  profiles:
    active: dev

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  jdbc.template.fetch-size: 100

pizza:
  orders:
    sizePage: 2
  show:
    page: 0