spring:
  thymeleaf:
    cache: false
  datasource:
    generate-unique-name: false
    name: pizzaDb_h2

    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pizzaDb_h2
    username: sa
    password:

  profiles:
    active:
  jpa:
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

pizza:
  orders:
    sizePage: 2
  show:
    page: 0